### ISSUE TITLE
Can't work on NodeBB v1.17.0 

### ISSUE THREAD

**Issue by mzdluo123** [julianlam/nodebb-plugin-sso-github#15]
```
TypeError: Cannot read property 'length' of undefined
    at module.getObjectsFields (/home/nodebb/src/database/mongo/hash.js:123:15)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async User.getUsersFields (/home/nodebb/src/user/data.js:67:17)
    at async User.getUsersData (/home/nodebb/src/user/data.js:141:10)
    at async User.getUserData (/home/nodebb/src/user/data.js:136:17)
    at async getLastRestart (/home/nodebb/src/controllers/admin/dashboard.js:235:19)
    at async Promise.all (index 3)
    at async dashboardController.get (/home/nodebb/src/controllers/admin/dashboard.js:21:64)
    at async /home/nodebb/src/routes/helpers.js:61:5
(node:20490) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at module.getObjectsFields (/home/nodebb/src/database/mongo/hash.js:123:15)
    at Object.wrapperCallback [as getObjectsFields] (/home/nodebb/src/promisify.js:46:11)
    at User.getUsersFields (/home/nodebb/src/user/data.js:67:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async User.getUsersData (/home/nodebb/src/user/data.js:141:10)
    at async User.getUserData (/home/nodebb/src/user/data.js:136:17)
(node:20490) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20490) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20490) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
(node:20490) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at module.getObjectsFields (/home/nodebb/src/database/mongo/hash.js:123:15)
    at Object.wrapperCallback [as getObjectsFields] (/home/nodebb/src/promisify.js:46:11)
    at User.getUsersFields (/home/nodebb/src/user/data.js:67:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async User.getUsersData (/home/nodebb/src/user/data.js:141:10)
    at async User.getUserData (/home/nodebb/src/user/data.js:136:17)
(node:20490) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:20490) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at module.getObjectsFields (/home/nodebb/src/database/mongo/hash.js:123:15)
    at Object.wrapperCallback [as getObjectsFields] (/home/nodebb/src/promisify.js:46:11)
    at User.getUsersFields (/home/nodebb/src/user/data.js:67:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async User.getUsersData (/home/nodebb/src/user/data.js:141:10)
    at async User.getUserData (/home/nodebb/src/user/data.js:136:17)
(node:20490) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:20490) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 5)
(node:20490) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at module.getObjectsFields (/home/nodebb/src/database/mongo/hash.js:123:15)
    at Object.wrapperCallback [as getObjectsFields] (/home/nodebb/src/promisify.js:46:11)
    at User.getUsersFields (/home/nodebb/src/user/data.js:67:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async User.getUsersData (/home/nodebb/src/user/data.js:141:10)
    at async User.getUserData (/home/nodebb/src/user/data.js:136:17)
```
MongoDB Version  4.0.16

**Comment by HoshinoTented** [comment]
I got the same error :(

**Comment by julianlam** [comment]
Hi there, can you both please try the latest version v2.3.1? This may already be resolved.

**Comment by mzdluo123** [comment]
It works well.
Thank you!
